### ISSUE TITLE
unexpected indent in filter_3d.py

### ISSUE THREAD

**Issue by cvhammond** [davidpagnon/pose2sim#2]
While reviewing, it appears a tab was snuck into Pose2Sim/filter_3d.py at line 278. Upon un-tabbing the software worked as expected.

**Comment by davidpagnon** [comment]
Thank you for pointing this out, it has been corrected.

**Comment by davidpagnon** [comment]
Copied to old directory:
https://github.com/perfanalytics/pose2sim/issues/6
