### ISSUE TITLE
Index error when running Pose2Sim.track2D() on Linux 

### ISSUE THREAD

**Issue by lambdaloop** [davidpagnon/pose2sim#3]
When running Pose2Sim.track2D() within the Demo directory, I get the following error:
```File ~/builds/pose2sim/Pose2Sim/track_2d.py:253, in track_2d_all(config)
    250 frames_range = config.get('project').get('frames_range')
    252 calib_dir = os.path.join(project_dir, calib_folder_name)
--> 253 calib_file = glob.glob(calib_dir+'\*.toml')[0]
    254 pose_dir = os.path.join(project_dir, pose_folder_name)
    255 poseTracked_dir = os.path.join(project_dir, poseTracked_folder_name)

IndexError: list index out of range
```

It seems that the +"\*.toml" at that line should be replaced with os.path.join as in the neighboring lines. 
This should be replaced for both `track_2d_all` and `recap_tracking` functions.

**Comment by lambdaloop** [comment]
This is an issue within the `triangulate_3d.py` file as well.

**Comment by davidpagnon** [comment]
Thank you for pointing out this (stupid) mistake!

**Comment by davidpagnon** [comment]
Copied to new repository:
https://github.com/perfanalytics/pose2sim/issues/7
