### ISSUE TITLE
Community guidelines for contributing and seeking support are not clear

### ISSUE THREAD

**Issue by lambdaloop** [davidpagnon/pose2sim#4]
Following the [JOSS review](https://github.com/openjournals/joss-reviews/issues/4362), one of the items is:
> Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

However, I think the community guidelines are not clear. The closest is the following line at the top of the README: 
> Pull requests, suggestions, and issues are very welcome. [![GitHub issues](https://img.shields.io/github/issues/davidpagnon/pose2sim)](https://github.com/davidpagnon/pose2sim/issues)

In particular, it's unclear to me how to contribute. The pose2sim repository on the github does not have the code, and people outside of INRIA cannot comment on the [INRIA gitlab](https://gitlab.inria.fr/perfanalytics/pose2sim) .
Furthermore, it would be useful to have a code standard or some kind of guideline for contributing.

The README points to this issues page, which is clear enough. It is confusing to have separate github and a gitlab repositories for issues and code still.

I'm not sure where I should seek support. Is there a documentation website for this software? Is this github issues page the standard reference? It would help to specify this precisely.

**Comment by davidpagnon** [comment]
Copied issue to the new repository:
https://github.com/perfanalytics/pose2sim/issues/1
