### ISSUE TITLE
README should specify which version of OpenSim to install

### ISSUE THREAD

**Issue by lambdaloop** [davidpagnon/pose2sim#5]
It seems that there are multiple versions of OpenSim available to download from the reference link: https://simtk.org/frs/index.php?group_id=91

Is it safe to download the latest one (4.4 beta as of this writing)? It would be nice to specify which versions would work.

(Issue made as part of review for JOSS: https://github.com/openjournals/joss-reviews/issues/4362 )

**Comment by davidpagnon** [comment]
Pose2Sim works with all versions of OpenSim ≥ 4.0, including the latest 4.4 beta one (tested today). 
Readme.md has been updated to specify it.

**Comment by davidpagnon** [comment]
Copied to new directory:
https://github.com/perfanalytics/pose2sim/issues/5
